version: '3.3'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: chemisto/foodgram_backend:v1.7
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - backend
      - frontend

volumes:
  db_value:
  static_value:
  media_value: